package boundary;
import entity.*;
import controller.*;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : 用户输入输出类.java
//  @ Date : 2016/11/22
//  @ Author : 
//
//

import java.util.Scanner;

public class UserIo {
    public  String UserIn="";
    private String Result;
    public void userinput() 
    {
    	 @SuppressWarnings("resource")
		 Scanner theNowPoly = new Scanner(System.in);
    	 this.UserIn = theNowPoly.nextLine();
    }
    
    public void printresult() 
    {
         System.out.println(this.Result);
    }
    
    public void setresult(String result) 
    {
    	this.Result=result;
    }
    
    public static void  main(String[] args) {
        final UserIo myuser = new UserIo();
        MatchClass mymatch=new MatchClass();
        Expression myexpression=new Expression();
        String calcuR;
        while (!myuser.UserIn.equals("exit"))  { //输入exit，程序退出
          myuser.userinput();
          mymatch.setUserIn(myuser.UserIn);
          
          if(mymatch.match().equals("expression"))
          {
        	  myexpression.setExpression(mymatch.getUserIn());
        	  mymatch.setCalculateResult(myexpression.getExpression());
        	  
        	  myuser.setresult(mymatch.getCalculateResult());
        	  myuser.printresult();
          }
          else if(mymatch.match().equals("simplify"))
          {
        	  calcuR = myexpression.simplify(mymatch.getUserIn());
        	  mymatch.setCalculateResult(calcuR);
        	  
        	  myuser.setresult(mymatch.getCalculateResult());
        	  myuser.printresult();
          }
          else if(mymatch.match().equals("derivative"))
          {
        	  calcuR = myexpression.derivative(mymatch.getUserIn());
        	  mymatch.setCalculateResult(calcuR);
        	  
        	  myuser.setresult(mymatch.getCalculateResult());
        	  myuser.printresult();
          }
          else
          {
        	  calcuR="input error!";
        	  mymatch.setCalculateResult(calcuR);
        	  
        	  myuser.setresult(mymatch.getCalculateResult());
        	  myuser.printresult();
          }
        }

      }
}

