package controller;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ∆•≈‰¿‡.java
//  @ Date : 2016/11/22
//  @ Author : 
//
//

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class MatchClass {
    private String UserIn;
    private String CalculateResult;
    public String match() {
        String monomial = "(\\s*)(\\d+|[a-zA-Z]+(\\^\\d+)?)(\\s*)((\\*(\\s*)(\\d+|[a-zA-Z]+(\\^\\d+)?)(\\s*))*)";
		
		Pattern expressionP = Pattern.compile("(("+monomial+"){1}?)(((\\+|\\-)"+monomial+")*)");
		Matcher expressionM = expressionP.matcher(UserIn);
		
		Pattern simplifyP = Pattern.compile("!simplify((\\s*)([a-zA-Z]+=\\d+))*");
		Matcher simplifyM = simplifyP.matcher(UserIn);
		
		Pattern derivativeP = Pattern.compile("!d/d(\\s*)[a-zA-Z]+");
		Matcher derivativeM = derivativeP.matcher(UserIn);
		
		if(expressionM.matches())
		{
			 return "expression";
			
        }
		else if(simplifyM.matches())
		{
			return "simplify";
		}
		else if(derivativeM.matches())
		{
			return  "derivative";
		}
		else
		{
			return "input error!";
		}
	}
    
    public void setCalculateResult(String calculateResult) {
      this.CalculateResult=calculateResult;
    }
    
    public void setUserIn(String userin) 
    {
    	this.UserIn=userin;
    }
    
    public String getCalculateResult() 
    {
        return this.CalculateResult;
    }
    public String getUserIn()
    {
    	return this.UserIn;
    }
}
